[package]
name = "ergot-base"
version = "0.3.0"
authors = ["James Munns <james@onevariable.com>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/jamesmunns/ergot"
description = "The latest in unsafe network stacks"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
]
keywords = []
documentation = "https://docs.rs/ergot/"

[dependencies]
cobs        = "0.3.0"
cordyceps   = "0.3.4"
log         = "0.4.27"

critical-section    = { version = "1.2.0",  features = ["std"] }
maitake-sync        = { version = "0.2.1",  features = ["std"] }
mutex               = { version = "1.0.0",  features = ["std", "impl-critical-section"] }
postcard            = { version = "1.1.1",  features = ["use-std"] }
serde               = { version = "1.0",    features = ["derive"] }
tokio               = { version = "1.45.1", features = ["macros", "rt-multi-thread", "time", "io-util", "net", "sync"] }
heapless = "0.8.0"
