use std::{env, fs::File, io::Write, path::PathBuf};

fn main() {
    // `ergot::time` capabilities of the enabled backend features:
    // `time_now` to read the time, `time_sleep` to also wait.
    println!("cargo::rustc-check-cfg=cfg(time_now, time_sleep)");
    let feature = |name: &str| env::var_os(format!("CARGO_FEATURE_{name}")).is_some();
    let sleep = feature("TOKIO_STD") || feature("EMBASSY_TIME") || feature("WASM");
    if sleep {
        println!("cargo::rustc-cfg=time_sleep");
    }
    if sleep || feature("STD") {
        println!("cargo::rustc-cfg=time_now");
    }

    // Configure defmt sink buffer size
    println!("cargo:rerun-if-env-changed=DEFMT_SINK_BUFFER_SIZE");

    let size = env::var("DEFMT_SINK_BUFFER_SIZE")
        .map(|s| {
            s.parse()
                .expect("could not parse DEFMT_SINK_BUFFER_SIZE as usize")
        })
        .unwrap_or(256_usize);

    let out_dir_path = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let out_file_path = out_dir_path.join("defmt_sink_consts.rs");
    let mut out_file = File::create(&out_file_path).unwrap();

    out_file
        .write_all(
            format!(
                "// Generated by build.rs\npub const DEFMT_SINK_BUF_SIZE: usize = {};\n",
                size
            )
            .as_bytes(),
        )
        .unwrap();

    out_file.flush().unwrap();
}
