name: Build and Test Std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demos-std:
    name: "Build all std demos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #
      # STD demos
      #
      - name: Check ergot-base (no features, on host)
        working-directory: ./demos/std
        run: cargo build --all
