name: Build and Test no-std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demos-nostd:
    name: "Build all no-std demos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install thumbv7em target
        run: rustup target add thumbv7em-none-eabi
      - name: Install thumbv6m target
        run: rustup target add thumbv6m-none-eabi
      #
      # nRF52840 demos
      #
      - name: Check ergot (no features, on host)
        working-directory: ./demos/nrf52840
        run: cargo build --all
      #
      # RP2040 demos
      #
      - name: Check ergot (no features, on host)
        working-directory: ./demos/rp2040
        run: cargo build --all
