name: Build and Test Std Demos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demos-std:
    name: "Build all std demos"
    strategy:
      matrix:
        include:
          - os: windows-2022
          - os: ubuntu-latest
          - os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      #
      # STD demos
      #
      - name: Check std demos
        working-directory: ./demos/std
        run: cargo build --all
      #
      # Shared ICD
      #
      - name: Check shared icd
        working-directory: ./demos/shared-icd
        run: cargo build
