name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  miri:
    name: "Build all"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install embedded target
        # Note: once https://github.com/hawkw/mycelium/pull/538 lands we can test on
        # thumbv6m-none-eabi
        run: rustup target add thumbv7em-none-eabi
      #
      # ERGOT BASE
      #
      # no features, on std
      - name: Check ergot-base (no features, on host)
        run: cargo build
          working-directory: ./crates/ergot-base
      # std features, on std
      - name: Check ergot-base (std features, on host)
        run: cargo build --features=std
          working-directory: ./crates/ergot-base
      # no features, on mcu
      - name: Check ergot-base (no features, on mcu)
        run: cargo build --features=std --target=thumbv7em-none-eabi
          working-directory: ./crates/ergot-base
      #
      # ERGOT Prime
      #
      # no features, on std
      - name: Check ergot (no features, on host)
        run: cargo build
          working-directory: ./crates/ergot
      # std features, on std
      - name: Check ergot (std features, on host)
        run: cargo build --features=std
          working-directory: ./crates/ergot
      # no features, on mcu
      - name: Check ergot (no features, on mcu)
        run: cargo build --features=std --target=thumbv7em-none-eabi
          working-directory: ./crates/ergot
